#!/bin/bash
set -e

echo "[quik] Installing base tools..."
./curl.sh

echo "[quik] Installing Docker..."
./docker.sh

echo "[quik] Installing Minikube..."
./minikube.sh

echo "[quik] Installing Kubectl..."
./kubectl.sh

echo "[quik] Done! 🎉"
