#!/bin/bash
set -e

echo "[quik] Installing curl..."
sudo apt update 
sudo apt install -y curl

if [ -f ./docker.sh ]; then
    echo "Installing Docker..."
    chmod +x docker.sh
    ./docker.sh
else
    echo "Skipping Docker — docker.sh not found."
fi

if [ -f ./minikube.sh ]; then
    echo "Installing Minikube..."
    chmod +x minikube.sh
    ./minikube.sh
else
    echo "Skipping Minikube — minikube.sh not found."
fi

if [ -f ./kubectl.sh ]; then
    echo "Installing Kubectl..."
    chmod +x kubectl.sh
    ./kubectl.sh
else
    echo "Skipping Kubectl — kubectl.sh not found."
fi

echo "[quik] Done! Deleting installer... 🎉"
cd ~
rm -rf quik
cd ~
